eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8763
  tomcat:
    max-threads: 50
spring:
  application:
    name: service-order
feign:
  hystrix:
    enable: true